name: code_quest
description: Code Quest MVP (Flutter)
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0
  provider: ^6.0.5
  pdfx: ^2.6.0
  url_launcher: ^6.3.0
  google_fonts: ^6.1.0
  intl: ^0.19.0
  firebase_storage: ^11.6.1
  cloud_functions: ^4.7.6
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/data/mcq_data.json
    - assets/data/interview_material.json
    - assets/data/debug_questions.json
    - assets/data/aptitude_questions.json
    - assets/data/debug/basic.json
    - assets/data/mcq/os/
    - assets/data/mcq/dbms/
    - assets/data/mcq/cn/
    - assets/data/mcq/oop/
    - assets/data/mcq/dsa/
    - assets/data/mcq/cd/
    - assets/data/aptitude/quantitative/
    - assets/data/aptitude/logical/
    - assets/data/aptitude/verbal/
    - assets/interview_pdfs/sample.pdf
    

dependency_overrides:
