// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-2WMCynI59FYnrM0vAzcK2qHkC2SIBpE',
    appId: '1:359405049498:web:c6ebf1d4e8340643a77123',
    messagingSenderId: '359405049498',
    projectId: 'code-quest-6f22e',
    authDomain: 'code-quest-6f22e.firebaseapp.com',
    storageBucket: 'code-quest-6f22e.firebasestorage.app',
    measurementId: 'G-HGVEHLSJ2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3DYBCyKmANGRJK4xMe_b1u_qqXnmWr1A',
    appId: '1:359405049498:android:738943450b219fdca77123',
    messagingSenderId: '359405049498',
    projectId: 'code-quest-6f22e',
    storageBucket: 'code-quest-6f22e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyXCUrfFrvb1oFEBnlubUTcqMz8SbW1KM',
    appId: '1:359405049498:ios:ed4f04f5d398f073a77123',
    messagingSenderId: '359405049498',
    projectId: 'code-quest-6f22e',
    storageBucket: 'code-quest-6f22e.firebasestorage.app',
    iosBundleId: 'com.example.codeQuest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyXCUrfFrvb1oFEBnlubUTcqMz8SbW1KM',
    appId: '1:359405049498:ios:ed4f04f5d398f073a77123',
    messagingSenderId: '359405049498',
    projectId: 'code-quest-6f22e',
    storageBucket: 'code-quest-6f22e.firebasestorage.app',
    iosBundleId: 'com.example.codeQuest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-2WMCynI59FYnrM0vAzcK2qHkC2SIBpE',
    appId: '1:359405049498:web:b9e2394c58bf8030a77123',
    messagingSenderId: '359405049498',
    projectId: 'code-quest-6f22e',
    authDomain: 'code-quest-6f22e.firebaseapp.com',
    storageBucket: 'code-quest-6f22e.firebasestorage.app',
    measurementId: 'G-5QHD6EC2C6',
  );
}
